### ISSUE TITLE
"Only one authentication provider is supported. "

### ISSUE THREAD

**Issue by andyfangdz** [sourcegraph/issues#104]
#### Describe the question.
I saw in the [documentation](https://about.sourcegraph.com/docs/config/site#authproviders-array) for `auth.providers` it says "Only one authentication provider is supported." But since `auth.providers` is an array, is there a plan to support multiple providers? This would be really helpful in certain scenarios (e.g., admin accounts).

**Comment by sqs** [comment]
Yes, absolutely. There is a feature flag for this in site config (`..., ”experimentalFeatures”: {“multipleAuthProviders”: “enabled”}, ...`). When set, you can use configure and use multiple auth providers. It is experimental and we don’t recommend using this experimental feature in production or on a publicly accessible server yet.

Would love to hear more about your use case for this as we write up docs, etc., for it. Do you want admin accounts created as builtin accounts and to use SAML/OpenID Connect for all other users?

**Comment by andyfangdz** [comment]
Thanks for the quick response!

>Do you want admin accounts created as builtin accounts and to use SAML/OpenID Connect for all other users?
Yes, this is exactly the use case :)

**Comment by andyfangdz** [comment]
When I set `"multipleAuthProviders": "enabled"` with both builtin and http header and tried to access sourcegraph, sourcegraph gave me an error saying I must access through http header auth. :( Did I miss something else?

**Comment by sqs** [comment]
Ah, the `http-header` auth provider does not support being used as one of multiple auth providers (all of the other ones do, though: `builtin` `openidconnect` `saml`), because it is assumed that *all* HTTP access will be proxied via the auth proxy.

We can remove this assumption, though. Do you intend for admins to access Sourcegraph directly (not via the auth proxy)? Or does your auth proxy allow unauthenticated users to bypass it?

**Comment by andyfangdz** [comment]
ahh, very good point. I'm currently setting up sourcegraph without an auth proxy but planning to move it behind a proxy, hence the question :)

We do have a way to bypass the auth proxy if users have the correct permission setup elsewhere, and I think it would be convenient to bypass the proxy when doing maintenance, etc. It would be great if http headers could be supported in this way, but I see the point of not doing so :)

**Comment by sqs** [comment]
Great. :+1:  Your desired behavior will be in the next patch release. Thanks for the question!

**Comment by andyfangdz** [comment]
Awesome. Thanks!

**Comment by sqs** [comment]
We delayed this slightly to improve docs around the `http-header` auth provider. Should be out in a few days.
