### ISSUE TITLE
Chrome extension shows "Sign in to Sourcegraph"

### ISSUE THREAD

**Issue by mightyguava** [sourcegraph/issues#105]
- **Sourcegraph version:** 2.9.2 (17312_2018-06-21_23bc7be)
- **Platform:** Chrome Version 67.0.3396.99 (Official Build) (64-bit)

#### Steps to reproduce:

1. Sign out and back in to sourcegraph private instance
2. Navigate to private repo on github

#### Expected: 

View repository button: 
![image](https://user-images.githubusercontent.com/2769275/42383810-6ba1ff40-8106-11e8-9542-ee414efb2421.png)

#### Actual:

Sign in to Sourcegraph button: 
![image](https://user-images.githubusercontent.com/2769275/42383838-7c6bffb0-8106-11e8-94cf-6d257468805d.png)

The "View file" Buttons also don't show up.

**Comment by dadlerj** [comment]
Thanks for reporting @mightyguava

**Comment by KattMingMing** [comment]
@mightyguava - Are you still seeing this issue? If so, does the issue persist after refreshing the GitHub page?

**Comment by mightyguava** [comment]
@KattMingMing, yes I still see it. Can I provide any additional info? This only happens to me on private repos, not public ones.

**Comment by mightyguava** [comment]
My sourcegraph extension version is `v1.7.31`

**Comment by mightyguava** [comment]
I see an XHR from sourcegraph failing as 401 on every github page. Here's request/response copied out of the chrome debugger.

Request
```
curl 'https://sourcegraph.button-internal.com/.api/graphql?ResolveRev' -H 'Referer: https://github.com/' -H 'Origin: https://github.com' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data '{"query":"query ResolveRev($repoPath: String!, $rev: String!) {\n                repository(uri: $repoPath) {\n                    mirrorInfo {\n                        cloneInProgress\n                    }\n                    commit(rev: $rev) {\n                        oid\n                    }\n                }\n            }","variables":{"repoPath":"github.com/button/warehouse","rev":""}}' --compressed
```

Response
```
Response: Private mode requires authentication.
```

**Comment by babldev** [comment]
I was having this issue as well.

I believe the issue was that I have 3rd party cookies blocked in Chrome.
![screen shot 2018-07-17 at 9 15 35 am](https://user-images.githubusercontent.com/220799/42830999-04df4d4a-89a2-11e8-92a6-855c4447c5e0.png)
chrome://settings/content/cookies?search=cookie

To resolve the issue, I added the private domain to the "Allow" section.
![screen shot 2018-07-17 at 9 15 41 am](https://user-images.githubusercontent.com/220799/42831016-10d07322-89a2-11e8-92b4-b20927eb1568.png)
`[*.]sourcegraph.yourprivatedomainhere.net`

**Comment by KattMingMing** [comment]
@mightyguava - Can you check that the Sourcegraph site configuration has configured the corsOrigin.
```
"corsOrigin": "https://github.com",
```

**Comment by mightyguava** [comment]
It did not have it. Setting `corsOrigin` fixed it!

**Comment by KattMingMing** [comment]
@mightyguava Awsome! Glad that it’s resolved.
