### ISSUE TITLE
Does Sourcegraph support Identity provider initiated SAML SSO?

### ISSUE THREAD

**Issue by bbadger86** [sourcegraph/issues#106]
SAML SSO when initiated through SourceGraph login page works well but not when its initiated from the Identity Providers end. Looks like the difference is SourceGraph uses a RelayState parameter when its SP Initiated SAML while IdP initiated SAML does not pass that.

Any ideas?

**Comment by attfarhan** [comment]
Thanks for reporting @bbadger86. Will get our team to take a look at this.

**Comment by nimdanitro** [comment]
Would be interested in this too. 

I have tried to configure it on our IDP, but on sourcegraph I get the following error message:

```
frontend | t=2018-08-09T17:26:32+0000 lvl=eror msg="Error decoding SAML relay state." err="illegal base64 data at input byte 5"
```

The IDP is configured to send the relay state on IDP initiated SAML. Unfortunately, also with `INSECURE_SAML_LOG_TRACES=1` I cannot further debug this.

Any hints?

**Comment by beyang** [comment]
@nimdanitro Thanks for trying Sourcegraph and sorry to hear you're having difficulties. We've added more logging in a patch release: `sourcegraph/server:19267_2018-08-09_34abf0b_patch`. Can you try running with that and report what it prints after the log line that contains the text `SAML RelayState`. That should be a base64-encoded string, but it looks like the IdP response has an unexpected format.

Could you also let us know what SAML IdP you're using (e.g., Okta, Auth0, or something else) and what the configuration settings are like so we can try to reproduce on our end? Hope we can resolve this issue for you quickly!

**Comment by nimdanitro** [comment]
Thanks for the quick answer.

I've tried it and the realy state is just the plain entry URL of the sourcegraph application:

```
frontend | t=2018-08-10T06:53:04+0000 lvl=eror msg="Error decoding SAML relay state." err="illegal base64 data at input byte 48"
frontend | ======================================== SAML trace: SAML RelayState
frontend | https://sourcegraph.example.com/search
frontend | ========================================================
```

IDP wise, this is the default URL of the application. IMHO, there is a slight logic error in sourcegraph as it can be very well true that the RelayState is a base64 encoded token in the SP initiated login flow, but in the IDP flow, the relay state is usually used to signal the application which URL to open.

Please note, the SP initiated login flow works flawlessly, but we have a SSO portal, think https://sso.example.com which has a collection of links. Hence, a user can login to the sso portal and directly open the desired SAML application, e.g. Sourcegraph. This triggeres a IDP initiated login flow, as the SP does not redirect to the IDP (and thus no RelayState is available to the IDP). 

We can configure the IDP to send no relay state or send a certain URL as relay state. Therefore, I guess the easiest approach is that if no RelayState is send by the IDP, forward to the default route of sourcegraph, i guess it's sourcegraph.example.com/search

Or what exactly are you encoding in the relay state?

**Comment by beyang** [comment]
@nimdanitro thanks for the debugging info! We were able to successfully repro it against an Okta SAML instance and have fixed it in 2.10.2. Can you give that a try and let me know if that fixes the issue for you?

```
docker run --publish 7080:7080 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph --volume /var/run/docker.sock:/var/run/docker.sock sourcegraph/server:2.10.2
```

**Comment by beyang** [comment]
@bbadger86 the fix in version 2.10.2 should work for you, as well.

**Comment by nimdanitro** [comment]
I can confirm that 2.10.2 works fine for IDP initiated SAML login.

Thanks for the amazingly fast fix! Send my regards and thanks to the dev team

**Comment by beyang** [comment]
Thanks for helping us resolve the issue--let us know if you have any other feedback / feature requests!
