### ISSUE TITLE
[QA] How can I setting up gitlab ce 8.x with only api v3 in source graph

### ISSUE THREAD

**Issue by arthurkiller** [sourcegraph/issues#114]
#### Describe the question.
Now I am under gitlab ce 8.14.0 and only v3 api provide

How can I setting up gitlab ce 8.x with only api v3 in source graph

ps.I am  using sourcegraph docker newest docker image.

**Comment by dadlerj** [comment]
Hey @arthurkiller! Good question — GitLab only introduced personal access tokens in 8.8 (see https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html)

This unfortunately means that our easy `gitlab` [configuration option](https://about.sourcegraph.com/docs/config/repositories#gitlab-configuration) won't work for you.

Instead, you need to use the `repos.list` [configuration option](https://about.sourcegraph.com/docs/config/repositories#sync-repositories-from-any-code-host), which allows you to specify the exact URL and path of each repository. Assuming your GitLab instance requires authentication, you will also need to [provide credentials](https://about.sourcegraph.com/docs/config/repositories#repositories-that-need-https-or-ssh-authentication) to Sourcegraph.

Let me know if the two documentation links above work for you.

**Comment by arthurkiller** [comment]
Thx for your reply. Added the repo list with each repo manually. And it works.

By the way, I read the log and it seems that only thing we need to do is change the gitlab api version from 4 to 3.Is that true?

Thx a lot.

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️

Arthur lee

**Comment by arthurkiller** [comment]
Yes , this issue should be closed.

**Comment by zemul** [comment]
error cloning repo: repo g.ktvsky.com/bigdata/vadd_gzh not cloneable: exit status 128

How do I import the old version of GITLAB project?
The above document is invalid.
Whether you should choose another Git host to import?
