### ISSUE TITLE
Error checking for updates: update endpoint returned HTTP error 400: "bad version string: strconv.Pa"

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/issues#116]
- **Sourcegraph version:** Sourcegraph Server v2.9.4 (v2.9.4)

#### Steps to reproduce:

1. Get excited that Sourcegraph 2.10.0 is released
2. Go to https://sourcegraph.example.com/site-admin/updates
3. See the error message

#### Expected: 
Sourcegraph tells you there's a new version

#### Actual:
> Error checking for updates: update endpoint returned HTTP error 400: "bad version string: strconv.Pa"

When looking at the requests, the POST to `/.api/graphql?SiteUpdateCheck` is made with:

```json
{
  "query": "
            query SiteUpdateCheck {
                site {
                    productName
                    buildVersion
                    productVersion
                    updateCheck {
                        pending
                        checkedAt
                        errorMessage
                        updateVersionAvailable
                    }
                }
            }
        ",
  "variables": {}
}
```

and the response is:

```json
{
  "data": {
    "site": {
      "productName": "Sourcegraph Server",
      "buildVersion": "v2.9.4",
      "productVersion": "v2.9.4",
      "updateCheck": {
        "pending": false,
        "checkedAt": "2018-08-02T20:02:26Z",
        "errorMessage": "update endpoint returned HTTP error 400: \"bad version string: strconv.Pa\"",
        "updateVersionAvailable": null
      }
    }
  }
}
```

**Comment by nicksnyder** [comment]
Thanks for reporting, can you post a screenshot of what you see on the updates page of your instance? e.g. http://sourcegraph.example.com/site-admin/updates

**Comment by nicksnyder** [comment]
Nevermind, I am able to reproduce

**Comment by nicksnyder** [comment]
The error with the update check endpoint is fixed, so this message will go away and you will see the update the next time the check is performed (approximately every 30 minutes).
