### ISSUE TITLE
Support rooting Sourcegraph at domain subdirectory

### ISSUE THREAD

**Issue by beyang** [sourcegraph/issues#119]
A user would like to be able to run Sourcegraph rooted at a URL like `http://example.org/source` (note the URL path). Our current URL structure makes it difficult to do this.

Proposal: add a config that allows Sourcegraph to be run under a URL path that's not `/`.

Initial user report: https://stackoverflow.com/questions/51223293/nginx-reverse-proxy-subdirectory-rewrites-for-sourcegraph

**Comment by dadlerj** [comment]
I believe this is a duplicate of https://github.com/sourcegraph/issues/issues/103

**Comment by beyang** [comment]
Closing as dup
