### ISSUE TITLE
How to create user by curl with token?

### ISSUE THREAD

**Issue by erhu** [sourcegraph/issues#122]
It works in API Console to create user with this script:

```
mutation{
  createUser(username:"abc",email:"abc@gmail.com") {
  	resetPasswordURL
  }
}
```

But, How to create user by `curl` with token. this command was failed:

```
curl -H 'Authorization: token cee342ca8f9e21ebb60fbe3d303fceb60e8c8984' \
-d '{"mutation": "mutation { createUser (username:'abc', email:'abc@gmail.com') {resetPasswordURL}}"}' http://source.xxx.com/.api/graphql
```

 Thanks~

**Comment by nicksnyder** [comment]
Two changes to your curl command will make it work:

1. The top level key in the json object needs to be `query` not `mutation` (cc @slimsag should we alias mutation too?)
2. You need to use escaped double quotes in the graphql query instead of single quotes

```
curl -H 'Authorization: token cee342ca8f9e21ebb60fbe3d303fceb60e8c8984' \
-d '{"query": "mutation { createUser (username:\"abcd\", email:\"email2.com\") {resetPasswordURL}}"}' \
http://localhost:3080/.api/graphql
```

**Comment by erhu** [comment]
Thanks a lot, it works :)
