### ISSUE TITLE
What value is the bitbucketServer.certificate parameter expecting?

### ISSUE THREAD

**Issue by Raman325** [sourcegraph/issues#150]
#### Describe the question.
I apologize in advance if this is a dumb question, but the documentation says that value of the bitbucketServer.certificate parameter is a string and says it is the certificate. What is the actual value to put in? Is it a path to the cert file? The actual key itself? Something else?

#### Is your question related to a problem? If so, please describe or link to another issue.
I am trying to point Sourcegraph to a local BitBucket server, which is using an internally signed certificate, and I am getting a "certificate signed by unknown authority" error. I am trying to figure out how to get Sourcegraph to trust the certificate, but the documentation isn't very clear and I can't find any examples.

Appreciate the help!

**Comment by nicksnyder** [comment]
The value should be the actual key itself (e.g. starts with `-----BEGIN CERTIFICATE-----`)

I agree that our docs should be more clear about this (some cert configurations or documented better but this one seems to have been missed).

**Comment by Raman325** [comment]
Thanks @nicksnyder and how does that work as a multiline string? I tried removing line breaks but SourceGraph doesn't seem to like that

**Comment by Raman325** [comment]
I added \n between lines and made it a single string which seemed to work!
