### ISSUE TITLE
Trouble adding already-cloned repo

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/issues#151]
- **Sourcegraph version:** ?
- **Platform:** ?

#### Steps to reproduce:

Reported by a user:

>Hi
>
>Reading https://about.sourcegraph.com/docs/config/repositories/#add-repositories-already-cloned-to-disk
>
>I have a valid already cloned repo in

`~/.sourcegraph/data/repos/github.com/monortc`

>I configured repo

```
"repos.list": [
  { 
    "url": "file:///var/opt/sourcegraph/repos/github.com/monortc",
    "path": "monorepo"
  }
]
```

>See image
>
>But I get errors that repo is empty

![image](https://user-images.githubusercontent.com/5589410/45965497-7bc53700-bfdd-11e8-99c1-78abe57c9de4.png)
![image](https://user-images.githubusercontent.com/5589410/45965503-7e279100-bfdd-11e8-9a7d-2012991ac091.png)
![image](https://user-images.githubusercontent.com/5589410/45965509-7ff15480-bfdd-11e8-8839-3987ad75711e.png)
![image](https://user-images.githubusercontent.com/5589410/45965514-8253ae80-bfdd-11e8-8fdc-da2017471eec.png)

**Comment by nicksnyder** [comment]
It needs to be a bare checkout, not a regular checkout.

This is what it should look like:

```
$ ls ~/.sourcegraph/data/repos/github.com/monortc
HEAD		description	info		packed-refs
config		hooks		objects		refs
```

Follow the instructions in step 2 exactly

**Comment by mulyoved** [comment]
Thanks, using --mirror seems to work, can close the issue
