### ISSUE TITLE
Fix Markdown rendering

### ISSUE THREAD

**Issue by beyang** [sourcegraph/issues#16]
Markdown rendering broke after merging in latest changes from VS Code upstream.

Repro: https://sourcegraph.com/github.com/sgtest/markdown-images/-/blob/README.md#L14

**Comment by nicksnyder** [comment]
did you work on this @KattMingMing ?

**Comment by KattMingMing** [comment]
@nicksnyder Nope, I thought @beyang did?

**Comment by beyang** [comment]
@nicksnyder I just pushed a patch. Still need a better long-term fix, though.

**Comment by sqs** [comment]
Fixed and deploying soon
