### ISSUE TITLE
Search in one file

### ISSUE THREAD

**Issue by ishitatsuyuki** [sourcegraph/issues#19]
Currently, when I press Ctrl+F, the inaccurate and hard to use browser search is triggered. I also found no way to search without entering the path of the file.

I'm requesting a similar in-file search experience compare to VS Code here.

**Comment by felixfbecker** [comment]
Hi @ishitatsuyuki, what OS and browser are you using?
In Chrome on macOS, I can use <kbd>Cmd</kbd>+<kbd>F</kbd> to trigger in-file search.

You can also trigger it and see the assigned shortcut by pressing <kbd>F1</kbd> and typing "Find".
If the assigned keyboard shortcut doesn't work in your browser, you can reassign it through <kbd>F1</kbd>, "Preferences: Open keyboard shortcuts".

Hope this helps!

**Comment by ishitatsuyuki** [comment]
I'm using Chrome 59 on Windows 10. I guess Ctrl+F is identical to Cmd+F on Mac. It triggered the browser version of search.

**Comment by ishitatsuyuki** [comment]
I couldn't reproduce this on Linux so I guess it's my configuration or extension issue. I will reopen this when I encounter it again.
