### ISSUE TITLE
.c++ extension is not recognized

### ISSUE THREAD

**Issue by ishitatsuyuki** [sourcegraph/issues#25]
It's widely used in [capnproto](https://github.com/capnproto/capnproto/search?l=c%2B%2B).

**Comment by beyang** [comment]
Thanks for filing. We don't recognize the extension, because we don't yet support code navigation (jump-to-def, find-refs, etc.) for C++.

Closing this as a duplicate of https://github.com/sourcegraph/issues/issues/10, but feel free to re-open if I misunderstood the issue.
