### ISSUE TITLE
The search feature  shouldn't simply showing the result from Github search feature.

### ISSUE THREAD

**Issue by zheeeng** [sourcegraph/issues#29]
I'm gonna search some code through SourceGraph, e.g.: https://sourcegraph.com/github.com/thinkjs/thinkjs@2.x

This is the `2.x` branch of `thinkjs`, not the master branch. The Github search feature can't get me the result of old branches. And the SourceGraph also don't get me the result of `2.x` branch instead of the master branch.

**Comment by felixfbecker** [comment]
Hi @zheeeng, I'm working on the new search box. UI for searching arbitrary revisions is high on my todo!

**Comment by rothfels** [comment]
@zheeeng this feature has been shipped. Given your example, try a query like `repo:^github\.com/thinkjs/thinkjs$@2.x  test`

More documentation on search query syntax here: https://about.sourcegraph.com/docs/search
