### ISSUE TITLE
Partial results displayed in external reference search

### ISSUE THREAD

**Issue by samuelhug** [sourcegraph/issues#31]
When doing an external reference search like the following, the results count increases over time as the asynchronous query returns results but only the first three are displayed.

https://sourcegraph.com/github.com/golang/crypto@HEAD/-/blob/ssh/client.go#L19:6$references:external

The PC I'm currently testing on:
Windows 10 x64
Google Chrome 63.0.3239.84 64bit

**Comment by keegancsmith** [comment]
cc @rothfels @slimsag

**Comment by rothfels** [comment]
Thanks for the report @samuelhug. I suspect this is an issue with how we render results (an "infinite list" which dynamically loads new entries as you scroll). If possible, provide a gif/screencast of what you see since I am not  able to reproduce on my laptop screen/external monitor.

**Comment by samuelhug** [comment]
Here is a screen recording of the issue. https://i.imgur.com/2bbYlLl.gif

The first few times I scroll down it only displays the first 5 results even though it has others. This time it did eventually display more results on the 5th time I scrolled down.

**Comment by slimsag** [comment]
Hi @samuelhug, I've just fixed this issue. Thank you for the screen recording!

Sorry that you ran into this bug, and for the delay! If you see any other strange behavior, please just let me know and I'll reopen / investigate. 😃
