### ISSUE TITLE
no syntax highlighting on many common file types

### ISSUE THREAD

**Issue by sqs** [sourcegraph/issues#42]
- [x] Makefiles should be syntax highlighted - example: https://sourcegraph.com/github.com/pallets/flask/-/blob/docs/Makefile (not highlighted) - via @creack 
- [x] `.vue` files (example: https://sourcegraph.com/search?q=repo:vuejs/vue+file:%5C.vue%24+Home) via https://twitter.com/zuoez02/status/987300504190386177
- [x] `.editorconfig` files (example: https://sourcegraph.com/github.com/editorconfig/editorconfig-vscode@master/-/blob/.editorconfig#L14)
- [x] `.Gopkg.lock` files (example: https://sourcegraph.com/github.com/golang/dep@master/-/blob/Gopkg.lock)

**Comment by creack** [comment]
If we could extend that to `.editorconfig`, toml files and `Gopkg.lock` (toml as well), it would be awesome :)

**Comment by slimsag** [comment]
@creack FYI, Makefiles are now syntax highlighted as of the latest 2.8 version (the others remain to be done still):

![image](https://user-images.githubusercontent.com/3173176/40747270-a0ebe2ae-6411-11e8-8b49-1c8736325c4b.png)

**Comment by slimsag** [comment]
> .vue files [...]

I've looked into this just now, but due to an upstream bug the existing Vue.js syntax highlighting file for Sublime appears to not work with the syntax highlighting library we use. It looks like this will be hard to track down / resolve. See https://github.com/trishume/syntect/issues/176

**Comment by slimsag** [comment]
Great news! I've added support for all of these (including Vue.JS files!).

It is live now on sourcegraph.com, and will be available to users of Sourcegraph Server & Data Center in the next release :) I've added support for:

- Rust files: [example](https://sourcegraph.com/github.com/sourcegraph/syntect_server/-/blob/src/main.rs)
- TOML files: [Gopkg.toml example](https://sourcegraph.com/github.com/golang/dep/-/blob/Gopkg.toml), [Cargo.lock example](https://sourcegraph.com/github.com/sourcegraph/syntect_server/-/blob/Cargo.lock), [Gopkg.lock example](https://sourcegraph.com/github.com/golang/dep/-/blob/Gopkg.lock)
- Protobuf files: [example](https://sourcegraph.com/github.com/google/protobuf@master/-/blob/examples/addressbook.proto#L32)
- GraphQL files: [example](https://sourcegraph.com/github.com/xpepermint/graphql-example@master/-/blob/src/graph/schema/index.graphql)
- Vue.JS files: [exampe](https://sourcegraph.com/github.com/vuejs/vue-cli/-/blob/packages/@vue/cli-plugin-typescript/generator/template/src/views/Home.vue#L20:10)
- `.editorconfig` files: [example](https://sourcegraph.com/github.com/editorconfig/editorconfig-vscode@master/-/blob/.editorconfig#L14)

In addition to some much needed bug fixes for syntax highlighting in general :)
