### ISSUE TITLE
Run sourcegraph outside of docker

### ISSUE THREAD

**Issue by choudhary001** [sourcegraph/issues#46]
- Issue type: question

I went through the installation [guide](https://about.sourcegraph.com/docs/server) where it says docker is a pre-requisite. Can sourcegraph server run outside of docker? Is it possible to run it on a standalone linux box (not on hosted services like aws, google etc.) and for git repositories hosted on personal gitlab and gitolite servers?

**Comment by nicksnyder** [comment]
> Can sourcegraph server run outside of docker?
Sourcegraph Server is a single node installation that requires docker. You just need to download and install docker for your operating system to get it running on any machine.

We also have Sourcegraph Data Center which runs on a full Kubernetes cluster for when you need to scale to a large team and a large amount of code.

> Is it possible to run it on a standalone linux box (not on hosted services like aws, google etc.)

Yes! Just have docker installed on any machine and run the docker command in the guide.

> for git repositories hosted on personal gitlab and gitolite servers?

Yes! After you have Sourcegraph Server running, you can configure it to point to your code host.

See the guide here: https://about.sourcegraph.com/docs/server/config/repositories

Scroll to the bottom of the guide for an gitolite example.

Hope that helps!
