### ISSUE TITLE
how about run via docker-compose

### ISSUE THREAD

**Issue by Wilbeibi** [sourcegraph/issues#47]
- Issue type: bug report/question
- Sourcegraph version: 2.5.17
- OS Version: MacOS 10.13.3
- Docker version: 18.03.0-ce-rc1-mac54

Based on [issue41](https://github.com/sourcegraph/issues/issues/41), I managed to make it work by
map volume to /data/sourcegraph/config and /data/sourcegraph/data on docker-machine, but today when I rerun the container, it shows:

> frontend | DB not available: getting DB timezone: pq: database "sourcegraph" does not exist

Sure delete docker-machine volume could work, but I already added around 100 repositories, then I need to git clone them again.

I noticed there are several processes on this container, are there any reasons to do so instead of "one process one container"?

Thanks.

**Comment by nicksnyder** [comment]
Hi @Wilbeibi,

> frontend | DB not available: getting DB timezone: pq: database "sourcegraph" does not exist

Did the data get deleted somehow?

In general, you should be able to start/stop your Sourcegraph Server and as long as you point it to the same data path it should just work without any data loss.

> I noticed there are several processes on this container, are there any reasons to do so instead of "one process one container"?

Our system is composed of may processes because we have built Sourcegraph to scale. Our paid enterprise product (Sourcegraph Data Center) runs on a Kubernetes cluster.

The Sourcegraph Server product, which runs as a single docker command, bundles all that into a single container so it is easy to get started and try Sourcegraph for free on a single node.

**Comment by Wilbeibi** [comment]
> Did the data get deleted somehow?
I cannot confirm that (/bin/bash is disable for the container).

Thank you for your response, it make sense if single node purpose is for "free trial".

**Comment by nicksnyder** [comment]
@Wilbeibi Sourcegraph Server is a standalone free product that you can use forever, not just a "free trial"

If you are experiencing issues with data loss after restarting the server, let us know so we can fix!

**Comment by jaredstehler** [comment]
I'm seeing this same(?) issue starting sourcegraph in a brand new installation within an AWS ECS container. I'm using the standalone docker image `sourcegraph/server:2.6.8`

The very first message I see in the logs is:
```
[0;31m03:36:38 frontend | [0mDB not available: pq: database "sourcegraph" does not exist
[0;31m03:36:38 frontend | [0mTerminating frontend
[0;31m03:36:41 repo-updater | [0mt=2018-04-16T03:36:41+0000 lvl=warn msg="frontend not available at startup (will periodically try to reconnect)" err="frontend API not reachable: context deadline exceeded (last error: Get http://127.0.0.1:3090/.internal/ping: dial tcp 127.0.0.1:3090: connect: connection refused)"
```

I do see a populated `postgres` dir in my data dir:
```
sudo ls -la /mnt/efs/sourcegraph/data/postgresql/
total 128
drwx------ 19   70 root  6144 Apr 16 03:36 .
drwxrwxrwx  4 root root  6144 Apr 16 02:18 ..
drwx------  5   70   70  6144 Apr 16 02:19 base
drwx------  2   70   70  6144 Apr 16 02:19 global
drwx------  2   70   70  6144 Apr 16 02:18 pg_clog
drwx------  2   70   70  6144 Apr 16 02:18 pg_commit_ts
drwx------  2   70   70  6144 Apr 16 02:18 pg_dynshmem
-rw-------  1   70   70  4468 Apr 16 02:18 pg_hba.conf
-rw-------  1   70   70  1636 Apr 16 02:18 pg_ident.conf
drwx------  4   70   70  6144 Apr 16 02:18 pg_logical
drwx------  4   70   70  6144 Apr 16 02:18 pg_multixact
drwx------  2   70   70  6144 Apr 16 03:36 pg_notify
drwx------  2   70   70  6144 Apr 16 02:18 pg_replslot
drwx------  2   70   70  6144 Apr 16 02:18 pg_serial
drwx------  2   70   70  6144 Apr 16 02:18 pg_snapshots
drwx------  2   70   70  6144 Apr 16 03:36 pg_stat
drwx------  2   70   70  6144 Apr 16 03:40 pg_stat_tmp
drwx------  2   70   70  6144 Apr 16 02:18 pg_subtrans
drwx------  2   70   70  6144 Apr 16 02:18 pg_tblspc
drwx------  2   70   70  6144 Apr 16 02:18 pg_twophase
-rw-------  1   70   70     4 Apr 16 02:18 PG_VERSION
drwx------  3   70   70  6144 Apr 16 02:18 pg_xlog
-rw-------  1   70   70    88 Apr 16 02:18 postgresql.auto.conf
-rw-------  1   70   70 22312 Apr 16 02:18 postgresql.conf
-rw-------  1   70   70    91 Apr 16 03:36 postmaster.opts
-rw-------  1   70   70    97 Apr 16 03:36 postmaster.pid
```

Is there anything else i can do to troubleshoot or get more detailed debug logging?

**Comment by sqs** [comment]
Moved to https://github.com/sourcegraph/issues/issues/60

**Comment by keegancsmith** [comment]
Bumping an old issue, but its top of google search for sourcegraph and docker compose :) We are starting to experiment with docker compose https://github.com/sourcegraph/deploy-sourcegraph-docker/tree/master/docker-compose
