### ISSUE TITLE
Error: Cannot Render Binary File on C# repo

### ISSUE THREAD

**Issue by wwaller** [sourcegraph/issues#51]
- Issue type: Bug report
- Sourcegraph version: sourcegraph.com

Steps to reproduce:

1. Go [here](https://sourcegraph.com/github.com/openhardwaremonitor/openhardwaremonitor@master/-/blob/GUI/NotifyIconAdv.cs) to NotifyIconAdv.cs of the OpenHardwareMonitor repo. Issue also happens with Utilities/EmbeddedResources.cs file in same repo, and Hardware/PInvokeDelegateFactory.cs, and Hardware/TBalancer/TBalancerGroup.cs. 
2. See "Error: Cannot render binary file".

My initial guess is the use of the DllImportAttribute in all the files except for EmbeddedResources.cs. But I'm not familiar enough with the implementation to know why that would be relevant.

![image](https://user-images.githubusercontent.com/4569537/37877740-1e9399ca-3025-11e8-80fb-b7781e085f33.png)

**Comment by keegancsmith** [comment]
The linked file is not valid UTF-8. The `ö` in Michael Möller is encoded as the single byte `0xF6`, which is invalid for UTF-8. Github is likely doing some sort of encoding detection on the file. You can see how your browser interprets the raw file to see it likely fails (atleast does on my system) https://raw.githubusercontent.com/openhardwaremonitor/openhardwaremonitor/e199e0ccc69b4da92495266ebc0faf7daad97608/GUI/NotifyIconAdv.cs

We currently expect UTF-8 in all files. I am guessing our binary file detector could be a bit more lenient, and the syntax highlighter may just work.

**Comment by nicksnyder** [comment]
Potentially related to https://github.com/sourcegraph/issues/issues/32
