### ISSUE TITLE
404 Page with Custom Domain

### ISSUE THREAD

**Issue by emresaracoglu** [sourcegraph/issues#52]
- Issue type: question
- Sourcegraph version: 2.6.8
- OS Version: 7.2
- Docker version: Latest
   
Hi,

I wrote the Custom Domain address into the Confirmation file and reset the server. 

```
{
    // ...
    "appURL": "https://domain.example.com",
    // ...
}
```

Same time, I have updated the Nginx file of the domain.

```
upstream sourcegraph {
    server 192.168.1.76:7080;
}
server {
proxy_redirect off; 
location ~* .*/$ {
    proxy_pass http://sourcegraph;
    proxy_set_header Connection "";
    proxy_http_version 1.1;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
}
}
```

When I go to this address: `https://domain.example.com `
the domain name is automatically changed with it. `https://domain.example.com/sign-in?returnTo=%2F`

> On the page I get 404 page
> Not Found
> The requested URL /sign-in was not found on this server.
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

What could be the reason for this?
Thank you.

**Comment by nicksnyder** [comment]
> proxy_pass http://sourcegraph

I am not familiar with how to configure nginx, but that line look suspicious to me.

If you remove "appURL" from your config, can you access sourcegraph by hitting the public IP of your machine directly?

What are your TLS settings?
https://about.sourcegraph.com/docs/server/config/tlsssl/#docs-content

**Comment by emresaracoglu** [comment]
Hi @nicksnyder 

I re-setup for a clean work and I did not add the appURL line but it did not change.

**Comment by emresaracoglu** [comment]
Now,

I added "appURL", TLS key and TLS Cert line. The server was restarted.
Result: I can not log in to the system. It does not give any errors (on IP address).

Could you please, can you say what is the location of the confirmation file?

**Comment by nicksnyder** [comment]
What do you see when you can't log on to the system? Can you post screenshots?

Can you email me your full site config (redact any access tokens)?

nick@sourcegraph.com

**Comment by emresaracoglu** [comment]
My username & password is correct, I am trying to log in and do not see any errors. No action.
This time I get the wrong information. I get a message my password is incorrect.
For this reason I deleted this deploy but I re-setup.

How do I get to the config file?

**Comment by nicksnyder** [comment]
It looks like you have gotten into a state where the first admin account has been created, but the credentials that you have provided are not correct.

Here are some steps to try on the machine that is running Sourcegraph:
1. Get the Docker container id for Sourcegraph
    ```
    $ docker ps
    CONTAINER ID        IMAGE
    d039ec999761        sourcegraph/server:2.6.8
    ```
2. Check the database to make sure you have the correct username
    ```
    docker exec -it d039ec999761 psql -U postgres sourcegraph --expanded -c 'select * from users'
    ```
3. Cat the site config (this is also available at http://localhost:7080/site-admin/configuration after you sign in)
    ```
    docker exec d039ec999761 cat /etc/sourcegraph/sourcegraph-config.json
    ```

If that doesn't lead you to a solution, then I would stop Sourcegraph, delete the data and config dirs, and start it again. The you should be able to create a new account that is the admin. For example:
```
rm -rf $HOME/.sourcegraph/config $HOME/.sourcegraph/data
docker run \
 --publish 7080:7080 --rm \
 --volume $HOME/.sourcegraph/config:/etc/sourcegraph \
 --volume $HOME/.sourcegraph/data:/var/opt/sourcegraph \
 sourcegraph/server:2.6.8
```

**Comment by emresaracoglu** [comment]
I changed the port number because Nginx is installed on the server. Therefore I changed it:

{
  "appURL": "https://example.domain.com:8443"
}

and I can access with the domain name :)
**Thank you for your time & help**
