### ISSUE TITLE
Usernames from SSO-Provider with dots

### ISSUE THREAD

**Issue by dloxtermann** [sourcegraph/issues#55]
- Issue type: feature request
- Sourcegraph version: 2.6.8
- OS Version: Ubuntu Server 16.04
- Docker version:
```
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I'm using the bitly-oauth proxy with GitLab (own hosting).
So far i could set this up to work, **but**:

The usernames in my company use dots to seperate first and last name (e.g. john.doe). Apparently sourcegraph does not allow dots in usernames (i couldn't find this restriction anywhere in the docs - it just fails with a log entry from postgres, saying that the username check failed).

As i can't just change everyones username i created this feature-request.
 
Steps to reproduce:

1. Setup any SSO Provider
2. Try to login using a username like john.doe

**Comment by sqs** [comment]
We merged a fix for this bug and it will be in the next patch release. Thank you for reporting it!

**Comment by nicksnyder** [comment]
This should be fixed in the latest release, please reopen if you continue to experience issues.
