### ISSUE TITLE
New ECS install fails with DB not available: pq: database "sourcegraph" does not exist

### ISSUE THREAD

**Issue by jaredstehler** [sourcegraph/issues#60]
- Issue type: bug report
- Sourcegraph version: sourcegraph/server:2.6.8
- OS Version: Amazon ECS-Optimized Amazon Linux AMI 2017.09.l
- Docker version:
```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:	Tue Apr  3 23:37:44 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6/17.12.1-ce
  Built:	Tue Apr  3 23:38:52 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

I'm seeing this issue starting sourcegraph in a brand new installation within an AWS ECS container. I'm using the standalone docker image `sourcegraph/server:2.6.8`

The very first message I see in awslogs is:
```
[0;31m03:36:38 frontend | [0mDB not available: pq: database "sourcegraph" does not exist
[0;31m03:36:38 frontend | [0mTerminating frontend
[0;31m03:36:41 repo-updater | [0mt=2018-04-16T03:36:41+0000 lvl=warn msg="frontend not available at startup (will periodically try to reconnect)" err="frontend API not reachable: context deadline exceeded (last error: Get http://127.0.0.1:3090/.internal/ping: dial tcp 127.0.0.1:3090: connect: connection refused)"
```

I do see a populated `postgres` dir in my data dir:
```
sudo ls -la /mnt/efs/sourcegraph/data/postgresql/
total 128
drwx------ 19   70 root  6144 Apr 16 03:36 .
drwxrwxrwx  4 root root  6144 Apr 16 02:18 ..
drwx------  5   70   70  6144 Apr 16 02:19 base
drwx------  2   70   70  6144 Apr 16 02:19 global
drwx------  2   70   70  6144 Apr 16 02:18 pg_clog
drwx------  2   70   70  6144 Apr 16 02:18 pg_commit_ts
drwx------  2   70   70  6144 Apr 16 02:18 pg_dynshmem
-rw-------  1   70   70  4468 Apr 16 02:18 pg_hba.conf
-rw-------  1   70   70  1636 Apr 16 02:18 pg_ident.conf
drwx------  4   70   70  6144 Apr 16 02:18 pg_logical
drwx------  4   70   70  6144 Apr 16 02:18 pg_multixact
drwx------  2   70   70  6144 Apr 16 03:36 pg_notify
drwx------  2   70   70  6144 Apr 16 02:18 pg_replslot
drwx------  2   70   70  6144 Apr 16 02:18 pg_serial
drwx------  2   70   70  6144 Apr 16 02:18 pg_snapshots
drwx------  2   70   70  6144 Apr 16 03:36 pg_stat
drwx------  2   70   70  6144 Apr 16 03:40 pg_stat_tmp
drwx------  2   70   70  6144 Apr 16 02:18 pg_subtrans
drwx------  2   70   70  6144 Apr 16 02:18 pg_tblspc
drwx------  2   70   70  6144 Apr 16 02:18 pg_twophase
-rw-------  1   70   70     4 Apr 16 02:18 PG_VERSION
drwx------  3   70   70  6144 Apr 16 02:18 pg_xlog
-rw-------  1   70   70    88 Apr 16 02:18 postgresql.auto.conf
-rw-------  1   70   70 22312 Apr 16 02:18 postgresql.conf
-rw-------  1   70   70    91 Apr 16 03:36 postmaster.opts
-rw-------  1   70   70    97 Apr 16 03:36 postmaster.pid
```

Is there anything else i can do to troubleshoot or get more detailed debug logging?

**Comment by jaredstehler** [comment]
FYI I also tried adding the env `DB_STARTUP_TIMEOUT=2m` but it still failed with the same message, albeit after 2m.

**Comment by sqs** [comment]
Thanks for the report and sorry you're experiencing this issue!

Were those `/mnt/efs/sourcegraph/data/postgresql` files created by a prior instance of the container? If there was an error in creating the DB, the prior instance of the container would have exited with a log that contains `Setting up postgres failed:`. Did you try removing those files and restarting the container (in case creating the DB crashed for some reason)?

We'll investigate if none of these things help.

(In general, the env var `SRC_LOG_LEVEL=dbug` will cause more log messages to be printed, but that won't actually help in this case.)

**Comment by jaredstehler** [comment]
the postgres files didnt exist prior to starting the container. I have tried removing them and restarting, with same result.

**Comment by adam-moss** [comment]
I seem to recall having a similar issue to do with selinux

`chcon -Rt svirt_sandbox_file_t /path/to/volume`

**Comment by jaredstehler** [comment]
@adam-moss does the `chcon` command have to be to the specific dir I'm mounting, or could it be a parent-/grandparent-dir?

**Comment by adam-moss** [comment]
To the actual mount I believe, or you could try putting the `:Z` option on your `--volume` parameters

**Comment by jaredstehler** [comment]
So I was able to get sourcegraph to boot successfully, by switching to an ephemeral ECS mount for data. I'm not sure how to specify the `:Z` option in the ECS task definition.

```
      {
        Name: 'data-vol',
        Host: {}
      }
```


At first redis failed to start due to a missing dir, so I changed the redis configured dir to be `/var/opt/sourcegraph` instead of `/var/opt/sourcegraph/redis`.

**Comment by jaredstehler** [comment]
I think this ended up being an issue of cpu cycles; I had been granting the container cpu `512`; when I switched it to `2048` things started up fine.

**Comment by sqs** [comment]
Thanks for the followup and glad it was able to start up. We will look into why it did not properly wait for initialization to be finished.

**Comment by peter-grainger** [comment]
@jaredstehler could you post your ecs task.json config.

It would give me a bit of a head start (and would probably help others who have the same issue)

Thanks.

**Comment by jaredstehler** [comment]
sure, if this helps anyone:

```yaml
resource :SourcegraphECSTaskDefinition, 'AWS::ECS::TaskDefinition' do
  family 'sourcegraph-service'
  cpu '2048'
  memory '3096'
  container_definitions \
    [
      {
        Name: 'sourcegraph-service',
        Essential: true,
        Image: 'sourcegraph/server:2.7.0',
        Cpu: "2048",
        Memory: "3096",
        PortMappings: [
          {
            ContainerPort: 7080
          }
        ],
        Environment: [
          { Name: 'SRC_LOG_LEVEL', Value: 'debug' }
        ],
        Privileged: true,
        Ulimits: [
          {
            Name: 'nofile',
            HardLimit: 102400,
            SoftLimit: 102400
          }
        ],
        LogConfiguration: {
          LogDriver: 'awslogs',
          Options: {
            "awslogs-group": 'bz-ecs',
            "awslogs-region": AWS.region,
            "awslogs-stream-prefix": 'sourcegraph'
          }
        },
        MountPoints: [
          {
            SourceVolume: 'efs-config',
            ContainerPath: '/etc/sourcegraph'
          },
          {
            SourceVolume: 'efs-data',
            ContainerPath: '/var/opt/sourcegraph'
          }
        ]
      }
    ]
  volumes \
    [
      {
        Name: 'efs-config',
        Host: {
          SourcePath: '/mnt/efs/sourcegraph/config'
        }
      },
      {
        Name: 'efs-data',
        Host: {
          SourcePath: '/mnt/efs/sourcegraph/data'
        }
      }
    ]
end
```

**Comment by peter-grainger** [comment]
👍 @jaredstehler
