### ISSUE TITLE
Hovertext marked too far down

### ISSUE THREAD

**Issue by seebs** [sourcegraph/issues#62]
- Issue type: bug report
- Sourcegraph version: sourcegraph.com
- OS Version: linux
- Docker version: N/A

Steps to reproduce:

1. https://sourcegraph.com/github.com/sourcegraph/go-langserver/-/blob/langserver/internal/godef/godef.go#L141:36
2. hover over ast.StarExpr on line 141.
3. Notice how there's two empty strings, and the text between them is italicized.
4. Realize that a StarExpr is probably an expression starting with "\*" (an asterisk), and that this was instead interpreted as markdown for italics between the two references to that quoted asterisk.

**Comment by beyang** [comment]
Thanks for filing, we'll get this fixed in the next iteration!

**Comment by felixfbecker** [comment]
Unfortunately there is no way to detect whether a comment is intended to be markdown or plain text. We either can interpret them all as markdown with some not-nice edge cases or only support plain text. Given the popularity of markdown in comments and most LSP clients/language servers behaving this way (interpreting comments as markdown) the former seems to be the better trade-off.
