### ISSUE TITLE
gitserver error: "Failed to update repository's Git remote URL" and remote repository URL is incorrect

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/issues#76]
- Issue type: Bug report
- Sourcegraph version: 2.7.6 (15051_2018-05-08_e88fa63) `sourcegraph/server:insiders`
- OS Version: amzn2-ami-hvm-2017.12.0.20180328.1-x86_64-gp2 (ami-07eb707f)
- Docker version:
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Tue Nov 14 22:03:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   402dd4a/17.06.2-ce
 Built:        Tue Nov 14 22:04:39 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

In our logs, we are noticing the following error from `gitserver`:
```
lvl=eror msg="Failed to update repository's Git remote URL." repo=github.example.com/user/repo url=https://github.example.com/user/repo
```

In addition, if we go to the repository page (https://sourcegraph.example.com/github.example.com/user/repo), it claims that it is an "Empty repository".

If we go to the Mirror settings page (https://sourcegraph.example.com/github.example.com/user/repo/-/settings/mirror), Sourcegraph the reported remote repository URL is pointing to another repository, _i.e._ https://github.example.com/something/totally/different

How are remote repositories determined and how can I help you narrow down the bug?

**Comment by nicksnyder** [comment]
@sfllaw The latest insiders build includes more error information in the log message. Can you update and let us know what the new log message says?

**Comment by sfllaw** [comment]
@nicksnyder I'm now running 15251_2018-05-11_14b0a8c and `gitserver` is still reporting the same type of error message:

```
t=2018-05-11T21:52:58+0000 lvl=eror msg="Failed to update repository's Git remote URL." repo=github.example.com/user/repo url=https://github.example.com/user/repo error="exit status 128"
```

Should I be looking for something else?

**Comment by nicksnyder** [comment]
The extra `error="exit status 128"` was what we were looking for, thanks!

**Comment by keegancsmith** [comment]
If there is a codehost configured for `github.example.com` then we use that configuration for generating the remote URL. If there isn't we fallback to checking what the origin URL is in the clone.

We are currently addressing our git/codehost architecture. It's evolved into a place where the above log line can occur, even though there is nothing actually wrong. I'll work on a short-term fix to reduce the logspam due to this. Is there anything user noticeable related to the log lines?

**Comment by keegancsmith** [comment]
@sfllaw I am hoping the latest insiders build has resolved this for you. If it does keep complaining about a repository I have two questions:

* Would it be managed by a repo configuration you have (ie would it be returned in the List operation done against the codehost with the token provided)
* Does the error for the repository go away if you visit it?

**Comment by sfllaw** [comment]
@keegancsmith This is still happening in 15680_2018-05-18_2d07482.

* **Would it be managed by a repo configuration you have (ie would it be returned in the List operation done against the codehost with the token provided)**

  It is managed by the List operation done against the codehost. I'm pretty sure GitHub Enterprise isn't lying about the repository.

  For instance, we have a repo called github.example.com/user/repo, and we can ask the GitHub API about it:

  ```console
  slaw@mittens:~$ http --verify=no --follow https://github.example.com/api/v3/repos/user/repo \
      'Authorization: token c0ffee' \
      | jq '{clone_url: .clone_url, html_url: .html_url}'
  {
    "clone_url": "https://github.corp.qc/aabeledo/fiat_cleanr.git",
    "html_url": "https://github.corp.qc/aabeledo/fiat_cleanr"
  }
  ```

  However, the https://sourcegraph.example.com/github.example.com/user/repo/-/settings/mirror page will sometimes report the *Remote Repository URL* as `(unknown)` or some other random repository. If the remote repository is unknown, that page will report `Error: repository not found` in the *Check Connection* section.

* **Does the error for the repository go away if you visit it?**

  No.

  When it is reporting another repository as the Remote Repository URL, visiting the Sourcegraph repository page at https://sourcegraph.example.com/github.example.com/user/repo will show the following errors:

  >Unable to list directory contents
  >`exec [git ls-tree --long --full-name -z 6fe00b91e11ab5c70bccec4741f10121d918a2b4] failed: exit statu`
  >
  >Revision not found: 
  >github.example.com/user/repo@6fe00b91e11ab5c70bccec4741f10121d918a2b4 revision not found: github.example.com/user/repo@6fe00b91e11ab5c70bccec4741f10121d918a2b4

  It looks like it is picking the hash of some other repo's master branch.

**Comment by keegancsmith** [comment]
@sfllaw sorry about that, but this bug seems a lot more insidious than I initially thought. It does indeed seem like we are chopping and changing the remote URL, or somehow we are asking our git infra for the wrong repo. Time to turn on the firehose of debug info. Can you run sourcegraph with these environment variables:

```
SRC_LOG_LEVEL=debug
SRC_GITSERVER_TRACE=t
```

the logs then for `repo-updater` and `gitserver` will be of interest. I think this little bit of sed should clean out your logs of creds

```
sed -E 's|(https?://)[^/?#@ ]*@|\1REDACTED@|g'
```

**Comment by sqs** [comment]
@sfllaw 2.8.9 contains a number of fixes to make this part of the code more robust. Are you still seeing this issue occur?

**Comment by sfllaw** [comment]
@sqs Things seem significantly more reliable now in 2.8.9, I can't reproduce the bug so I'm going to close this.
