### ISSUE TITLE
unrecognized HTTP Authorization request header scheme (supported values: token, token-sudo)

### ISSUE THREAD

**Issue by seshness** [sourcegraph/issues#84]
- **Issue type:** bug report
- **Sourcegraph version:** 2.8.0
- **Platform:**

#### Steps to reproduce:

1. Run Sourcegraph in Docker.
2. Configure Sourcegraph with HTTP header authentication.
3. Run bit.ly's oauth2_proxy, configuring Sourcegraph as the backend.

#### Expected: 
Automatically signed in to Sourcegraph when accessed from a browser, through oauth2_proxy.

#### Actual:
```
19:52:11       frontend | ✱ Sourcegraph is ready at: https://sourcegraph.<domain>
19:52:34       frontend | t=2018-05-22T19:52:34+0000 lvl=eror msg="Invalid Authorization header." err="unrecognized HTTP Authorization request header scheme (supported values: token, token-sudo)"
```
I don't see any references to `token` or `token-sudo` in https://about.sourcegraph.com/docs/config/site.

Sourcegraph configuration excerpt:
```
      "auth.providers": [
        {
          "type": "http-header",
          "usernameHeader": "X-Forwarded-User"
        }
      ],
```

Sorry this bug report is light on details - if there are any specific details about our instance of Sourcegraph / bit.ly's oauth2_proxy configuration needed to debug this, I'm happy to share them privately.

**Comment by sqs** [comment]
Thanks for the report. Is your HTTP auth proxy setting an `Authorization` header in addition to the `X-Forwarded-User` header? Sourcegraph rejects requests with unrecognized `Authorization` with the error message you saw. Can you configure your auth proxy to not send this header?

We just now updated https://about.sourcegraph.com/docs/config/authentication#http-authentication-proxies to mention this. Also looking into `oauth2_proxy` to see how to configure it to not send this header. Sorry for the disruption!

**Comment by seshness** [comment]
Thanks for the quick response!

Removing the authorization header fixes the issue. For `oauth2_proxy`, the `-pass-basic-auth` flag needs to be set to `false`. By default this flag is set to `true`.
