### ISSUE TITLE
Browser extension seemingly breaks github project boards

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/issues#93]
- **Sourcegraph version:** Browser extension v1.7.19
- **Platform:** macOS 10.13.5, Chrome 67.0.3396.79

#### Steps to reproduce:

1. Go to any project board on github
2. Open the "add card" menu

#### Expected: 

Usual behavior 

#### Actual:

The Add card menu overlays everything and the boards are unusable

![image](https://user-images.githubusercontent.com/19534377/41196230-4ceedf26-6bf0-11e8-9491-51a07d74f2b2.png)

**Comment by dadlerj** [comment]
Thanks for the report! We'll get this fixed ASAP

**Comment by KattMingMing** [comment]
@eseliger - This issue has been resolved and shipped in 1.7.20, you should see the extension update within a couple of hours. Thanks again for your report and let us know if you have additional feedback!

**Comment by eseliger** [comment]
Thanks for the quick fix 🙂
