### ISSUE TITLE
configure repos toast even when using code host

### ISSUE THREAD

**Issue by terinjokes** [sourcegraph/issues#94]
- **Sourcegraph version:** 2.8.9 (server)
- **Platform:**
  - **Code Host**: Bitbucket Server

#### Steps to reproduce:

1. Setup a Sourcegraph Server instance
2. Configure Bitbucket Server code host
3. Repos clone :tada: 
4. Administrators still see the "Configure repositories and code hosts
 to add to Sourcegraph Server." toast.

#### Expected: 

Toast goes away. Sort-of like [ihob](https://lite.cnn.io/en/article/h_c7c283e19c58f6a8dd4a2b5fb00c8c53).

#### Actual:

You keep getting toast, even when you want burgers.

**Comment by nicksnyder** [comment]
Thanks for reporting, I have a fix ready to commit!

**Comment by terinjokes** [comment]
I can confirm this is fixed in 2.9.x.
