### ISSUE TITLE
Logs contain "show-ref failed" errors for every empty repository

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/issues#96]
- **Sourcegraph version:** 2.8.9

#### Steps to reproduce:

1. Create an empty GitHub Enterprise repository (github.example.com/user/empty-repo)
2. Enable it in Sourcegraph
3. Watch the logs

#### Expected: 
Logs are silent about repositories with no commits.

#### Actual:
Logs contain tons of repeated messages about `git show-ref` failing, which it would on a repository with no commits.
```
22:26:57 gitserver | t=2018-06-14T22:26:57+0000 lvl=eror msg="show-ref failed" repo=github.example.com/user/empty-repo error="exit status 1" output=
```

**Comment by nicksnyder** [comment]
@sfllaw can you confirm that this is fixed for you?

**Comment by sfllaw** [comment]
Fixed.
